# Generated by Django 5.2.2 on 2025-07-06 20:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='RFC')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('nivel_educativo', models.CharField(blank=True, choices=[('SEC', 'Secundaria'), ('TEC', 'Técnico / Preparatoria'), ('LIC', 'Licenciatura'), ('MAE', 'Maestría'), ('DOC', 'Doctorado'), ('OTR', 'Otro')], max_length=3, null=True, verbose_name='Máximo Nivel Educativo')),
                ('años_de_experiencia', models.PositiveIntegerField(blank=True, null=True, verbose_name='Años de Experiencia Profesional')),
                ('ultimo_puesto', models.CharField(blank=True, max_length=200, verbose_name='Último Puesto Desempeñado')),
                ('ultima_empresa', models.CharField(blank=True, max_length=200, verbose_name='Última Empresa donde Laboró')),
                ('motivo_busqueda', models.CharField(blank=True, choices=[('DESAFIO', 'Desafío personal'), ('CREC', 'Crecimiento profesional'), ('SALARIO', 'Mejor salario'), ('CULTURA', 'Cultura empresarial saludable')], max_length=10, verbose_name='Razón por la que buscas nuevas oportunidades')),
                ('es_colaborador_actual', models.BooleanField(default=False, verbose_name='Ya soy colaborador de Premier')),
                ('habilidades', models.TextField(blank=True, help_text='Ej: Liderazgo, Excel Avanzado, Ventas, SAP, etc. (separadas por comas)', null=True, verbose_name='Habilidades Principales')),
                ('expectativa_salarial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Expectativa Salarial Mensual (Bruta)')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Puesto')),
            ],
            options={
                'verbose_name': 'Puesto de Catálogo',
                'verbose_name_plural': 'Catálogo de Puestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Aviso')),
                ('contenido', models.TextField(verbose_name='Contenido del Aviso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('esta_activo', models.BooleanField(default=True, verbose_name='¿Aviso Activo?')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Aviso General',
                'verbose_name_plural': 'Avisos Generales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcas', models.ManyToManyField(blank=True, to='reclutamiento.marca')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aprobacion_gerente_marca', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Aprobación Gerente de Marca')),
                ('fecha_aprobacion_director', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Aprobación Director')),
                ('agencia', models.CharField(max_length=100, verbose_name='Agencia')),
                ('area', models.CharField(choices=[('VTAS', 'Ventas'), ('SERV', 'Servicio'), ('REF', 'Refacciones'), ('ADM', 'Administración'), ('OTRA', 'Otra')], max_length=4, verbose_name='Área')),
                ('ciudad', models.CharField(choices=[('CUL', 'Culiacán'), ('MZT', 'Mazatlán'), ('LMM', 'Los Mochis'), ('GVE', 'Guasave'), ('CJM', 'Cajeme'), ('HMO', 'Hermosillo'), ('MXL', 'Mexicali'), ('TIJ', 'Tijuana'), ('LPZ', 'La Paz'), ('LCB', 'Los Cabos'), ('CDMX', 'CDMX'), ('MTY', 'Monterrey')], max_length=100, verbose_name='Ciudad de la Vacante')),
                ('cantidad_vacantes', models.PositiveIntegerField(default=1, verbose_name='Cantidad de Vacantes Solicitadas')),
                ('experiencia_minima', models.PositiveIntegerField(blank=True, help_text='Años de experiencia requeridos para el puesto.', null=True, verbose_name='Experiencia Mínima (años)')),
                ('carrera_sugerida', models.CharField(blank=True, max_length=200, verbose_name='Carrera o Especialidad Sugerida')),
                ('reemplaza_a', models.CharField(blank=True, max_length=200, verbose_name='Nombre de la persona a quien reemplaza (si aplica)')),
                ('nombre_jefe_inmediato', models.CharField(max_length=200, verbose_name='Nombre del Jefe Inmediato')),
                ('puesto_jefe_inmediato', models.CharField(max_length=200, verbose_name='Puesto del Jefe Inmediato')),
                ('motivo_requisicion', models.CharField(choices=[('ROT', 'Rotación de Personal'), ('INC', 'Incremento de Plantilla'), ('INCA', 'Cubrir Incapacidad')], max_length=4, verbose_name='Motivo de la Requisición')),
                ('objetivo_puesto', models.TextField(verbose_name='Objetivo/Propósito del Puesto')),
                ('funciones_puesto', models.TextField(help_text='Listar las 5 funciones más importantes.', verbose_name='Actividades o Funciones Principales (5)')),
                ('indicador_puesto', models.TextField(verbose_name='Indicador más relevante con el que se mide el puesto')),
                ('herramientas_puesto', models.CharField(help_text="Puede colocar 'No aplica'.", max_length=255, verbose_name='Herramientas específicas de uso (Office, programas, etc.)')),
                ('conocimientos_tecnicos', models.CharField(help_text="Puede colocar 'No aplica'.", max_length=255, verbose_name='Conocimientos técnicos específicos')),
                ('horario', models.CharField(max_length=100, verbose_name='Horario a cubrir')),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sueldo Base Mensual (Bruto)')),
                ('esquema_comisiones', models.TextField(blank=True, verbose_name='Esquema de comisiones y/o bonos (si aplica)')),
                ('archivo_justificacion', models.FileField(blank=True, help_text='Anexa un correo o documento que respalde la solicitud (PDF, Word, etc.)', null=True, upload_to='justificaciones/', verbose_name='Archivo de Justificación (Opcional)')),
                ('es_confidencial', models.BooleanField(default=False, verbose_name='¿Es una vacante confidencial?')),
                ('estatus_autorizacion', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación de Gerente de Marca'), ('PENDIENTE_DIR', 'Pendiente de Aprobación de Dirección'), ('AUTORIZADO', 'Autorizado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_segunda_autorizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Segunda Aprobación')),
                ('esta_abierto', models.BooleanField(default=False)),
                ('aprobado_por_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puestos_aprobados_dir', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por Director')),
                ('aprobado_por_gerente_marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puestos_aprobados_gm', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por Gerente de Marca')),
                ('asesora_encargada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puestos_asignados', to=settings.AUTH_USER_MODEL)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puestos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reclutamiento.marca', verbose_name='Marca')),
                ('segundo_autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puestos_segunda_autorizacion', to=settings.AUTH_USER_MODEL, verbose_name='Segunda Aprobación Por')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puestos_solicitados', to=settings.AUTH_USER_MODEL)),
                ('titulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reclutamiento.catalogopuesto', verbose_name='Nombre del Puesto Vacante')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('FB', 'Facebook'), ('IG', 'Instagram'), ('LI', 'LinkedIn'), ('OCC', 'OCC Mundial'), ('CT', 'Computrabajo'), ('OTRA', 'Otra')], max_length=4, verbose_name='Plataforma')),
                ('enlace', models.URLField(max_length=500, verbose_name='Enlace al Post')),
                ('monto_inversion', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Monto de Inversión (MXN)')),
                ('fecha_publicacion', models.DateField(default=django.utils.timezone.now)),
                ('publicado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='reclutamiento.puesto')),
            ],
            options={
                'verbose_name': 'Publicación de Vacante',
                'verbose_name_plural': 'Publicaciones de Vacantes',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus_proceso', models.CharField(choices=[('NUEVO', 'Nuevo'), ('INTEG', 'Examen de Integridad'), ('PSICO', 'Examen de Psicometría'), ('REF', 'Validación de Referencias'), ('ENT_AS', 'Entrevista con Asesora'), ('ENT_JF', 'Entrevista con Jefe Inmediato'), ('MEDIC', 'Exámenes Médicos'), ('DOCS', 'Solicitud de Documentos'), ('FIRMA', 'Firma de Contrato'), ('ALTA', 'Alta en Sistemas (Contabilidad, GMM, etc.)'), ('INGRESO', 'Fecha de Ingreso Confirmada'), ('NO_PSICO', 'No Aprobado (Psicometría/Integridad)'), ('EN_BOLSA', 'En Bolsa de Trabajo (No Continuó)'), ('CONTRATADO', 'Contratado (Cierra Vacante)')], default='NUEVO', max_length=20, verbose_name='Estatus del Proceso')),
                ('fecha_inicio_etapa', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio de Etapa')),
                ('retroalimentacion', models.TextField(blank=True)),
                ('asesora_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Asesora Asignada')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='reclutamiento.candidato', verbose_name='Candidato')),
                ('puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reclutamiento.puesto', verbose_name='Puesto Aplicado')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilDePuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_edad', models.CharField(blank=True, max_length=50, verbose_name='1. Rango de edad ideal')),
                ('preferencia_sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('I', 'Indistinto')], default='I', max_length=1, verbose_name='2. ¿Preferencia de sexo?')),
                ('motivo_preferencia_sexo', models.CharField(blank=True, choices=[('DES', 'Afecta el desempeño'), ('COS', 'Costumbre'), ('OTR', 'Otro motivo')], max_length=3, null=True, verbose_name='3. Motivo de la preferencia')),
                ('area_experiencia_enfoque', models.CharField(choices=[('VTAS', 'Ventas/Comercial'), ('SERV', 'Servicio al cliente'), ('ADM', 'Administrativo'), ('OPE', 'Operativo (Taller)')], max_length=4, verbose_name='4. ¿En qué área de experiencia nos enfocamos más?')),
                ('importancia_apariencia', models.CharField(choices=[('ALTA', 'Importa mucho'), ('BAJA', 'No importa')], max_length=4, verbose_name='5. ¿Qué importancia tiene la apariencia personal?')),
                ('justificacion_apariencia', models.TextField(blank=True, verbose_name='5a. Si importa mucho, ¿por qué?')),
                ('feedback_anterior', models.TextField(blank=True, verbose_name='6. ¿Qué te gustaría que se repitiera y qué no del ocupante anterior?')),
                ('requiere_licencia', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='7. ¿Requiere licencia y saber conducir estándar?')),
                ('comentarios_adicionales', models.TextField(blank=True, verbose_name='Comentarios adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('puesto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_detallado', to='reclutamiento.puesto')),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='puesto_de_interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reclutamiento.puesto', verbose_name='Puesto de Interés'),
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=255, verbose_name='Acción Realizada')),
                ('tipo_objeto', models.CharField(blank=True, max_length=50, null=True)),
                ('id_objeto', models.PositiveIntegerField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True, null=True, verbose_name='Detalles Adicionales (Notas)')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
