# Generated by Django 5.2.2 on 2025-07-25 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='interes_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Interés Personalizado'),
        ),
        migrations.AlterField(
            model_name='perfildepuesto',
            name='feedback_anterior',
            field=models.TextField(verbose_name='6. ¿Qué te gustaría que se repitiera y qué no del ocupante anterior?'),
        ),
        migrations.AlterField(
            model_name='perfildepuesto',
            name='rango_edad',
            field=models.CharField(max_length=50, verbose_name='1. Rango de edad ideal'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos', to='reclutamiento.puesto', verbose_name='Puesto Aplicado'),
        ),
    ]
