# Generated by Django 5.2.2 on 2025-07-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='es_colaborador_actual',
            field=models.BooleanField(default=False, verbose_name='Ya soy colaborador de Premier'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='expectativa_salarial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Expectativa Salarial Mensual (Bruta)'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='motivo_busqueda',
            field=models.CharField(blank=True, choices=[('DESAFIO', 'Desafío personal'), ('CREC', 'Crecimiento profesional'), ('SALARIO', 'Mejor salario'), ('CULTURA', 'Cultura empresarial saludable')], max_length=10, verbose_name='Razón por la que buscas nuevas oportunidades'),
        ),
    ]
