# Generated by Django 5.2.2 on 2026-09-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0002_candidato_interes_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo'),
        ),
    ]
