# Generated by Django 5.2.2 on 2026-09-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0003_puesto_motivo_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='agencia',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Agencia'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='esta_abierto',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='estatus_autorizacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación de Gerente de Marca'), ('PENDIENTE_DIR', 'Pendiente de Aprobación de Dirección'), ('AUTORIZADO', 'Autorizado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='PENDIENTE', max_length=20),
        ),
    ]
